version: '3.8'
services:
  gateway_mongo:
      image: mongo:latest
      container_name: gateway_mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin_password
        MONGO_INITDB_DATABASE: account
      ports:
        - "127.0.0.1:27017:27017"
      volumes:
        - type: volume
          source: MONGO_DATA
          target: /data/db
        - type: volume
          source: MONGO_CONFIG
          target: /data/configdb
  gateway_mongo-express:
      image: mongo-express:latest
      container_name: gateway_mongo-express
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
        MONGO_INITDB_DATABASE: account
        ME_CONFIG_MONGODB_SERVER: gateway_mongo
        ME_CONFIG_MONGODB_PORT: "27017"
        ME_CONFIG_BASICAUTH_USERNAME: dev@noksoft.com
        ME_CONFIG_BASICAUTH_PASSWORD: P@ssw0rdNokSoft
      ports:
        - "0.0.0.0:8081:8081"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile/go-dev.Dockerfile
    container_name: airsoft_gateway
    volumes:
      - './microservice:/app'
    working_dir: /app
    ports:
      - 8002:8000
volumes:
    MONGO_DATA:
    MONGO_CONFIG:
